// Generated by gencpp from file mmWave/data_frame.msg
// DO NOT EDIT!


#ifndef MMWAVE_MESSAGE_DATA_FRAME_H
#define MMWAVE_MESSAGE_DATA_FRAME_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mmWave
{
template <class ContainerAllocator>
struct data_frame_
{
  typedef data_frame_<ContainerAllocator> Type;

  data_frame_()
    : data()  {
    }
  data_frame_(const ContainerAllocator& _alloc)
    : data(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int16_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int16_t>> _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::mmWave::data_frame_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mmWave::data_frame_<ContainerAllocator> const> ConstPtr;

}; // struct data_frame_

typedef ::mmWave::data_frame_<std::allocator<void> > data_frame;

typedef boost::shared_ptr< ::mmWave::data_frame > data_framePtr;
typedef boost::shared_ptr< ::mmWave::data_frame const> data_frameConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mmWave::data_frame_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mmWave::data_frame_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mmWave::data_frame_<ContainerAllocator1> & lhs, const ::mmWave::data_frame_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mmWave::data_frame_<ContainerAllocator1> & lhs, const ::mmWave::data_frame_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mmWave

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mmWave::data_frame_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mmWave::data_frame_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mmWave::data_frame_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mmWave::data_frame_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mmWave::data_frame_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mmWave::data_frame_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mmWave::data_frame_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8560fbebb34fa1b9472337b5c3d38fda";
  }

  static const char* value(const ::mmWave::data_frame_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8560fbebb34fa1b9ULL;
  static const uint64_t static_value2 = 0x472337b5c3d38fdaULL;
};

template<class ContainerAllocator>
struct DataType< ::mmWave::data_frame_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mmWave/data_frame";
  }

  static const char* value(const ::mmWave::data_frame_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mmWave::data_frame_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16[] data\n"
;
  }

  static const char* value(const ::mmWave::data_frame_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mmWave::data_frame_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct data_frame_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mmWave::data_frame_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mmWave::data_frame_<ContainerAllocator>& v)
  {
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<int16_t>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MMWAVE_MESSAGE_DATA_FRAME_H
